const skill = (data) => data

const DOCS = {
  TypeScript: 'https://www.typescriptlang.org/docs/',
  React: 'https://react.dev/',
  'Node.js': 'https://nodejs.org/en/docs',
  Express: 'https://expressjs.com/',
  'PostgreSQL': 'https://www.postgresql.org/docs/',
  Redis: 'https://redis.io/docs/latest/',
  Docker: 'https://docs.docker.com/',
  'GSAP': 'https://gsap.com/docs/',
  'Framer Motion': 'https://www.framer.com/motion/',
  Vite: 'https://vite.dev/guide/',
  Linux: 'https://linux.die.net/',
  Git: 'https://git-scm.com/doc',
  Nginx: 'https://nginx.org/en/docs/',
  Kubernetes: 'https://kubernetes.io/docs/',
  Figma: 'https://help.figma.com/',
  GraphQL: 'https://graphql.org/learn/',
  Go: 'https://go.dev/doc/',
  MongoDB: 'https://www.mongodb.com/docs/',
  'Three.js': 'https://threejs.org/docs/',
  Prisma: 'https://www.prisma.io/docs',
  WebSockets: 'https://developer.mozilla.org/en-US/docs/Web/API/WebSockets_API',
  Tailwind: 'https://tailwindcss.com/docs',
  'Next.js': 'https://nextjs.org/docs',
  Python: 'https://docs.python.org/3/',
  Lua: 'https://www.lua.org/manual/5.4/',
  AWS: 'https://docs.aws.amazon.com/',
}

export const SKILL_LIBRARY = {
  typescript: skill({
    id: 'typescript',
    name: 'TypeScript',
    category: 'Language',
    yearsUsed: '4+ yrs',
    proficiency: 5,
    description: 'The glue for typed APIs, UI contracts, and tooling that does not drift.',
    useCases: ['Shared schemas', 'API clients', 'Tooling'],
    variant: 'v-accent',
    docsUrl: DOCS.TypeScript,
  }),
  nodejs: skill({
    id: 'nodejs',
    name: 'Node.js',
    category: 'Runtime',
    yearsUsed: '4+ yrs',
    proficiency: 5,
    description: 'Primary backend runtime for APIs, workers, and small command-line utilities.',
    useCases: ['HTTP services', 'Workers', 'CLI tools'],
    variant: 'v-ink',
    docsUrl: DOCS['Node.js'],
  }),
  express: skill({
    id: 'express',
    name: 'Express',
    category: 'Web framework',
    yearsUsed: '4+ yrs',
    proficiency: 5,
    description: 'My default HTTP layer for fast routes, middleware, and auth-heavy services.',
    useCases: ['REST APIs', 'Middleware stacks', 'Auth flows'],
    variant: 'v-accent',
    docsUrl: DOCS.Express,
  }),
  postgresql: skill({
    id: 'postgresql',
    name: 'PostgreSQL',
    category: 'Database',
    yearsUsed: '4+ yrs',
    proficiency: 5,
    description: 'Primary relational store for schema design, migrations, and query tuning.',
    useCases: ['Schema design', 'Query tuning', 'Migrations'],
    variant: 'v-ink',
    docsUrl: DOCS.PostgreSQL,
  }),
  redis: skill({
    id: 'redis',
    name: 'Redis',
    category: 'Cache / Queue',
    yearsUsed: '3+ yrs',
    proficiency: 4,
    description: 'Used for cache layers, queues, rate limits, and the occasional rescue rope.',
    useCases: ['Caching', 'Job queues', 'Rate limiting'],
    variant: 'v-accent',
    docsUrl: DOCS.Redis,
  }),
  docker: skill({
    id: 'docker',
    name: 'Docker',
    category: 'DevOps',
    yearsUsed: '3+ yrs',
    proficiency: 4,
    description: 'Keeps local and production environments boring in the best possible way.',
    useCases: ['Service isolation', 'Deploy parity', 'Local stacks'],
    variant: 'v-ink',
    docsUrl: DOCS.Docker,
  }),
  gsap: skill({
    id: 'gsap',
    name: 'GSAP',
    category: 'Motion',
    yearsUsed: '3+ yrs',
    proficiency: 4,
    description: 'The timing engine behind scroll reveals, sequencing, and interfaces with weight.',
    useCases: ['Scroll choreography', 'Sequence timing', 'Hero reveals'],
    variant: 'v-accent',
    docsUrl: DOCS.GSAP,
  }),
  framerMotion: skill({
    id: 'framer-motion',
    name: 'Framer Motion',
    category: 'Motion',
    yearsUsed: '3+ yrs',
    proficiency: 4,
    description: 'Gesture handling, transitions, and spring physics when the interface needs polish.',
    useCases: ['Gestures', 'Spring motion', 'Micro-interactions'],
    variant: 'v-ink',
    docsUrl: DOCS['Framer Motion'],
  }),
  vite: skill({
    id: 'vite',
    name: 'Vite',
    category: 'Build tool',
    yearsUsed: '3+ yrs',
    proficiency: 4,
    description: 'Fast local feedback loops and a clean build pipeline for modern React apps.',
    useCases: ['Builds', 'Dev server', 'Bundling'],
    variant: 'v-accent',
    docsUrl: DOCS.Vite,
  }),
  linux: skill({
    id: 'linux',
    name: 'Linux',
    category: 'Environment',
    yearsUsed: '5+ yrs',
    proficiency: 5,
    description: 'The daily operating system for shells, services, deploys, and the rest of the mess.',
    useCases: ['Shell work', 'Servers', 'Automation'],
    variant: 'v-ink',
    docsUrl: DOCS.Linux,
  }),
  git: skill({
    id: 'git',
    name: 'Git',
    category: 'Version control',
    yearsUsed: '5+ yrs',
    proficiency: 5,
    description: 'The least glamorous skill, which is exactly why it matters this much.',
    useCases: ['Branching', 'Code review', 'Release flow'],
    variant: 'v-accent',
    docsUrl: DOCS.Git,
  }),
  nginx: skill({
    id: 'nginx',
    name: 'Nginx',
    category: 'Web server',
    yearsUsed: '2+ yrs',
    proficiency: 4,
    description: 'Reverse proxying, static assets, and edge routing in front of the app.',
    useCases: ['Reverse proxy', 'Static delivery', 'Load balancing'],
    variant: 'v-white',
    docsUrl: DOCS.Nginx,
  }),
  kubernetes: skill({
    id: 'kubernetes',
    name: 'Kubernetes',
    category: 'Orchestration',
    yearsUsed: '2+ yrs',
    proficiency: 4,
    description: 'Container orchestration for repeatable deploys and saner scaling.',
    useCases: ['Deployments', 'Service discovery', 'Scaling'],
    variant: 'v-white',
    docsUrl: DOCS.Kubernetes,
  }),
  figma: skill({
    id: 'figma',
    name: 'Figma',
    category: 'Design',
    yearsUsed: '3+ yrs',
    proficiency: 4,
    description: 'Interface planning, layout exploration, and handoff for real builds.',
    useCases: ['Wireframes', 'UI systems', 'Prototyping'],
    variant: 'v-white',
    docsUrl: DOCS.Figma,
  }),
  graphql: skill({
    id: 'graphql',
    name: 'GraphQL',
    category: 'API Layer',
    yearsUsed: '2+ yrs',
    proficiency: 4,
    description: 'Typed query layer for data-heavy client/server contracts.',
    useCases: ['Schemas', 'Queries', 'Type-safe clients'],
    variant: 'v-ink',
    docsUrl: DOCS.GraphQL,
  }),
  go: skill({
    id: 'go',
    name: 'Go',
    category: 'Language',
    yearsUsed: '2+ yrs',
    proficiency: 4,
    description: 'Fast, simple services and tooling where concurrency matters.',
    useCases: ['CLI tools', 'APIs', 'Workers'],
    variant: 'v-white',
    docsUrl: DOCS.Go,
  }),
  typescriptAlt: skill({
    id: 'typescript-alt',
    name: 'TypeScript',
    category: 'Language',
    yearsUsed: '3+ yrs',
    proficiency: 5,
    description: 'Type-safe language for typed APIs, UI contracts, and tooling.',
    useCases: ['Typed APIs', 'Shared schemas', 'Tooling'],
    variant: 'v-ink',
    docsUrl: DOCS.TypeScript,
  }),
  mongodb: skill({
    id: 'mongodb',
    name: 'MongoDB',
    category: 'Database',
    yearsUsed: '2+ yrs',
    proficiency: 4,
    description: 'Document storage for flexible data shapes and evolving schemas.',
    useCases: ['Document models', 'Aggregation', 'Prototyping'],
    variant: 'v-white',
    docsUrl: DOCS.MongoDB,
  }),
  threejs: skill({
    id: 'threejs',
    name: 'Three.js',
    category: '3D',
    yearsUsed: '1+ yrs',
    proficiency: 3,
    description: 'WebGL scenes, camera motion, and 3D flourishes when the UI needs depth.',
    useCases: ['3D scenes', 'Materials', 'Spatial UI'],
    variant: 'v-ink',
    docsUrl: DOCS['Three.js'],
  }),
  drizzle: skill({
    id: 'drizzle',
    name: 'Drizzle',
    category: 'ORM',
    yearsUsed: '2+ yrs',
    proficiency: 4,
    description: 'Lightweight, type-safe ORM with SQL-like query builder for TypeScript apps.',
    useCases: ['Schemas', 'Migrations', 'Type-safe queries'],
    variant: 'v-accent',
    docsUrl: 'https://orm.drizzle.team/docs',
  }),
  websockets: skill({
    id: 'websockets',
    name: 'WebSockets',
    category: 'Realtime',
    yearsUsed: '2+ yrs',
    proficiency: 4,
    description: 'Realtime channels for live updates, presence, and push-driven UX.',
    useCases: ['Live updates', 'Presence', 'Streaming events'],
    variant: 'v-ink',
    docsUrl: DOCS.WebSockets,
  }),
  react: skill({
    id: 'react',
    name: 'React',
    category: 'UI Library',
    yearsUsed: '4+ yrs',
    proficiency: 5,
    description: 'Component-driven interfaces and interactive product surfaces.',
    useCases: ['Component systems', 'Stateful UIs', 'Design systems'],
    variant: 'v-accent',
    docsUrl: DOCS.React,
  }),
  tailwind: skill({
    id: 'tailwind',
    name: 'Tailwind',
    category: 'Styling',
    yearsUsed: '3+ yrs',
    proficiency: 5,
    description: 'Utility-first styling for quickly shipping polished UI systems.',
    useCases: ['Layout systems', 'Components', 'Responsive UI'],
    variant: 'v-white',
    docsUrl: DOCS.Tailwind,
  }),
  nextjs: skill({
    id: 'nextjs',
    name: 'Next.js',
    category: 'Framework',
    yearsUsed: '2+ yrs',
    proficiency: 4,
    description: 'React framework for full-stack rendering patterns and app routing.',
    useCases: ['Routing', 'Server rendering', 'App structure'],
    variant: 'v-white',
    docsUrl: DOCS['Next.js'],
  }),
  python: skill({
    id: 'python',
    name: 'Python',
    category: 'Language',
    yearsUsed: '2+ yrs',
    proficiency: 4,
    description: 'Automation, scripts, and data tasks where speed of writing matters.',
    useCases: ['Automation', 'Scripting', 'Data tooling'],
    variant: 'v-ink',
    docsUrl: DOCS.Python,
  }),
  lua: skill({
    id: 'lua',
    name: 'Lua',
    category: 'Language',
    yearsUsed: '1+ yrs',
    proficiency: 3,
    description: 'Embedded scripting where a small, fast runtime beats a whole toolchain.',
    useCases: ['Neovim config', 'Redis scripts', 'Gateway logic'],
    variant: 'v-white',
    docsUrl: DOCS.Lua,
  }),
  cicd: skill({
    id: 'cicd',
    name: 'CI/CD',
    category: 'Delivery',
    yearsUsed: '3+ yrs',
    proficiency: 4,
    description: 'Repeatable build and deploy pipelines for shipping with less drama.',
    useCases: ['Build pipelines', 'Deploys', 'Checks'],
    variant: 'v-accent',
  }),
  aws: skill({
    id: 'aws',
    name: 'AWS',
    category: 'Cloud',
    yearsUsed: '2+ yrs',
    proficiency: 4,
    description: 'Infrastructure building blocks for deployment, storage, and compute.',
    useCases: ['Compute', 'Storage', 'Deployment'],
    variant: 'v-ink',
    docsUrl: DOCS.AWS,
  }),
}

export const SKILL_ORDER = [
  'nginx',
  'docker',
  'redis',
  'typescript',
  'kubernetes',
  'figma',
  'postgresql',
  'gsap',
  'graphql',
  'go',
  'nodejs',
  'linux',
  'framerMotion',
  'typescriptAlt',
  'mongodb',
  'threejs',
  'drizzle',
  'websockets',
  'react',
  'tailwind',
  'nextjs',
  'git',
  'python',
  'lua',
  'cicd',
  'vite',
  'aws',
]

export const FALLBACK_SKILLS = SKILL_ORDER.map((key) => SKILL_LIBRARY[key])

const slugify = (value) =>
  String(value || '')
    .toLowerCase()
    .replace(/next\.js/g, 'nextjs')
    .replace(/framer motion/g, 'framermotion')
    .replace(/node\.js/g, 'nodejs')
    .replace(/[^a-z0-9]+/g, '')

export function buildSkillsFromRows(rows = []) {
  const byId = new Map(
    Object.values(SKILL_LIBRARY).map((item) => [slugify(item.id), item])
  )
  const byName = new Map(
    Object.values(SKILL_LIBRARY).map((item) => [slugify(item.name), item])
  )
  const seen = new Set()
  const ordered = []

  const push = (item) => {
    if (!item || seen.has(item.id)) return
    ordered.push(item)
    seen.add(item.id)
  }

  rows.forEach((row) => {
    const item = byId.get(slugify(row?.name)) || byName.get(slugify(row?.name))
    if (item) push(item)
  })

  FALLBACK_SKILLS.forEach(push)

  return ordered.slice(0, SKILL_ORDER.length)
}
